// generated by Claude AI

export const sampleData: Comment[] = [
  {
    id: 1,
    author: 'LAZP',
    content: 'WHO IS THE HANDSOME BOY IN THE PHOTO',
    timestamp: '19h ago',
    avatar: '🤖',
    replies: [
      {
        id: 2,
        author: 'LAZPLAZP',
        content: 'BRO, HE\'S YOU, YOU\'RE THE HANDSOME BOY IN THE PHOTO',
        timestamp: '19h ago',
        avatar: '🤖',
        replies: [
          {
            id: 3,
            author: 'LAZP',
            content: 'Really? no matter what you call me, I\'m the handsome boy in the photo.',
            timestamp: '19h ago',
            avatar: '👨',
            replies: [
              {
                id: 4,
                author: 'LAZPLAZP',
                content: 'You\'re right',
                timestamp: '6h ago',
                avatar: '👤',
                replies: []
              }
            ]
          }
        ]
      }
    ]
  },
  {
    id: 1,
    author: 'LAZP',
    content: 'WHO IS THE HANDSOME BOY IN THE PHOTO',
    timestamp: '19h ago',
    avatar: '🤖',
    replies: [
      {
        id: 2,
        author: 'LAZPLAZP',
        content: 'BRO, HE\'S YOU, YOU\'RE THE HANDSOME BOY IN THE PHOTO',
        timestamp: '19h ago',
        avatar: '🤖',
        replies: [
          {
            id: 3,
            author: 'LAZP',
            content: 'Really? no matter what you call me, I\'m the handsome boy in the photo.',
            timestamp: '19h ago',
            avatar: '👨',
            replies: [
              {
                id: 4,
                author: 'LAZPLAZP',
                content: 'You\'re right',
                timestamp: '6h ago',
                avatar: '👤',
                replies: []
              }
            ]
          }
        ]
      }
    ]
  }
];

export type Comment = {
  id: number;
  author: string;
  content: string;
  timestamp: string;
  avatar: string;
  replies: Comment[];
};